Static assets move public
rtCamp/wp-decoupled pull request #30
Opened 2021-01-13 06:32 UTC by NicestRudeGuy

### Changes
Moved `static` folder to `public` folder. No change in styles is required as it automatically fetches it as usual.   

### Note:
 Also removed the client-config-example as the we are now fetching its data from the .env

2021-01-13 07:01 UTC, m-muhsin approved these changes
LGTM

2021-01-13 15:12 UTC, imranhsayed requested changes
Why have we removed package-lock.json?

2021-01-14 05:19 UTC, NicestRudeGuy commented
> Why have we removed package-lock.json?

We do have package-lock.json file

2021-01-14 05:50 UTC, m-muhsin approved these changes

2021-01-14 10:22 UTC, merged